### ISSUE TITLE
Unable to encode when writing CSV file

### ISSUE THREAD

**Issue by Femez** [bayesimpact/python-emploi-store#25]
I've got a issue when I tried to export offers.
UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 74: character maps to <undefined>
then I put
k.encode('utf-8'): unicode(v).encode('utf-8','ignore')
instead of 
k.encode('utf-8'): unicode(v).encode('utf-8') 
at line 384 in __init__.py

**Comment by Femez** [comment]
Sorry, 'ignore' didn't work.

**Comment by pcorpet** [comment]
Thanks for reporting, this looks like a replacement character
I guess you're using python 2. I'm using version 3 so I didn't get that bug yet.

I'm going to investigate, but feel free to send a Pull Request if you find out before me.

**Comment by Femez** [comment]
Hello tanks for your response. 
I'm using python 3. I read the source too fast, this modification would never work.
I think it's a problem with the file source, now it's work because they updated the file. 
It's still happened with the package BMO ""Résultats enquête BMO 2017" , this file was clean few days ago. Now : 'charmap' codec can't encode character '\x85' in position 110: character maps to <undefined>
Maybe you can close the issue, I think it's impossible if the file is not clean.
