### ISSUE TITLE
La bonne Boite : Bad request

### ISSUE THREAD

**Issue by Femez** [bayesimpact/python-emploi-store#42]
Hello, 
I'm unable to get companies with client.get_lbb_companies()

import emploi_store
client = emploi_store.Client()
companies=client.get_lbb_companies(city_id='34172',rome_codes="M1607")
for i in companies:
       print(i)

HTTPError: 400 Client Error: BAD REQUEST for url: https://labonneboite.pole-emploi.fr/api/v1/company/?client_id=XXXXXXXXXXXXXXX&commune_id=34172&distance=10&origin_user=XXXX&rome_codes=M%2C1%2C6%2C0%2C7&timestamp=2020-07-28T13%3A36%3A24&user=emploi_store_dev&signature=XXXXXXXXXXXXX

I have got no problem whith other API like Infotravail v1 and I have already suscribe to this API 
![image](https://user-images.githubusercontent.com/38657411/88673358-cab3ea00-d0e8-11ea-8045-b3228ea19df3.png)

Thank you very much for your help.

**Comment by pcorpet** [comment]
Hi @Femez sorry for not answering earlier. If you're still trying, I believe you used a string for rome_codes instead of a list.

As I think that this is a common use case, I'll update the code to accept a string directly.

**Comment by pcorpet** [comment]
Note that you can fix your code quickly by calling:
```py
companies=client.get_lbb_companies(city_id='34172',rome_codes=["M1607"])
```
(note the square brackets around the rome code)
